{
    "gotoLine": {"key": "Ctrl-l", "mac": "Mod-l"},
    "historyBack": {"key": "Ctrl-Alt-ArrowLeft", "mac": "Ctrl-Mod-ArrowLeft"},
    "fold": {"key": "Alt-l", "mac": "Mod-Alt-l"},
    "unfold": {"key": "Alt-Shift-l", "mac": "Mod-Alt-Shift-l"},
    "saveDocument": {"key": "Ctrl-Shift-s", "mac": "Mod-Shift-s"},
    "runQuery": {"key": "Ctrl-Enter", "mac": "Mod-Enter"},
    "runQueryOrApp": {"key": "Ctrl-Shift-Enter", "mac": "Mod-Shift-Enter"},
    "openDocument": {"key": "Ctrl-Shift-o", "mac": "Mod-Shift-o"},
    "newDocumentFromTemplate": {"key": "Ctrl-Shift-n", "mac": "Mod-Shift-n"},
    "closeDocument": {"key": "Ctrl-Shift-w", "mac": "Mod-Alt-w"},
    "closeAll": {"key": "Ctrl-Alt-w", "mac": "Mod-Ctrl-w"},
    "autocomplete": {"key": "Ctrl-Space", "mac": "Ctrl-Space"},
    "nextTab": {"key": "Ctrl-Shift-PageDown", "mac": "Ctrl-Alt-ArrowRight"},
    "previousTab": {"key": "Ctrl-Shift-PageUp", "mac": "Ctrl-Alt-ArrowLeft"},
    "functionDoc": {"key": "F1"},
    "gotoDefinition": {"key": "F3"},
    "searchIncremental": {"key": "Ctrl-f", "mac": "Mod-f"},
    "searchReplace": {"key": "Ctrl-Shift-f", "mac": "Mod-Shift-f"},
    "indentOrParam": {"key": "Tab"},
    "escape": {"key": "Escape"},
    "dbManager": {"key": "Ctrl-Shift-m", "mac": "Mod-Shift-m"},
    "toggleComment": {"key": "Ctrl-Shift-c", "mac": "Mod-Shift-c"},
    "synchronize": {"key": "Alt-Shift-s", "mac": "Mod-Alt-s"},
    "preferences": {"key": "Alt-Shift-p", "mac": "Ctrl-Mod-p"},
    "openApp": {"key": "Ctrl-Alt-r", "mac": "Mod-Alt-r"},
    "xqueryFormat": {"key": "Ctrl-Shift-p", "mac": "Mod-Shift-p"},
    "quickfix": {"key": "Ctrl-.", "mac": "Ctrl-."},
    "expandSelection": {"key": "Ctrl-Shift-ArrowUp", "mac": "Ctrl-Mod-ArrowUp"},
    "renameSymbol": {"key": "Ctrl-Alt-r", "mac": "Mod-Ctrl-r"},
    "removeTags": {"key": "Ctrl-Alt-Backspace", "mac": "Mod-Alt-Backspace"},
    "extractFunction": {"key": "Ctrl-Shift-x", "mac": "Mod-Ctrl-x"},
    "extractVariable": {"key": "Ctrl-Shift-e", "mac": "Mod-Ctrl-e"},
    "gotoSymbol": {"key": "Ctrl-Shift-u", "mac": "Mod-Shift-u"},
    "openTab": {"key": "Ctrl-Alt-o", "mac": "Mod-Ctrl-o"},
    "toggleQueryResults": {"key": "Ctrl-Shift-e", "mac": "Mod-Shift-e"},
    "commandPalette": {"key": "Ctrl-Alt-k", "mac": "Mod-Shift-k"},
    "undo": {"key": "Ctrl-z", "mac": "Mod-z"},
    "redo": {"key": "Ctrl-Shift-z", "mac": "Mod-Shift-z"},
    "findFiles": {"key": "Ctrl-Alt-f", "mac": "Mod-Alt-f"},
    "gotoTab1": {"key": "Alt-1", "mac": "Ctrl-1"},
    "gotoTab2": {"key": "Alt-2", "mac": "Ctrl-2"},
    "gotoTab3": {"key": "Alt-3", "mac": "Ctrl-3"},
    "gotoTab4": {"key": "Alt-4", "mac": "Ctrl-4"},
    "gotoTab5": {"key": "Alt-5", "mac": "Ctrl-5"},
    "gotoTab6": {"key": "Alt-6", "mac": "Ctrl-6"},
    "gotoTab7": {"key": "Alt-7", "mac": "Ctrl-7"},
    "gotoTab8": {"key": "Alt-8", "mac": "Ctrl-8"},
    "gotoTab9": {"key": "Alt-9", "mac": "Ctrl-9"},
    "toggleDiagnostics": {"key": "Ctrl-Shift-d", "mac": "Mod-Shift-d"},
    "findReferences": {"key": "Shift-F3", "mac": "Shift-F3"}
}
