{
    "gotoLine": ["Ctrl-L", "Command-L"],
    "fold": ["Alt-L", "Alt-F"],
    "unfold": ["Alt-Shift-L", "Alt-Shift-F"],
    "saveDocument": ["Ctrl-Shift-S", "Command-Shift-S"],
    "runQuery": ["Ctrl-Return", "Command-Return"],
    "openDocument": ["Ctrl-Shift-O", "Command-Shift-O"],
    "newDocument": ["Ctrl-Shift-N", "Command-Shift-N"],
    "closeDocument": ["Ctrl-Shift-W", "Command-Option-W"],
    "autocomplete": ["Ctrl-Space", "Ctrl-Space"],
    "nextTab": ["Ctrl-Shift-PageDown", "Ctrl-Option-Right"],
    "previousTab": ["Ctrl-Shift-PageUp", "Ctrl-Option-Left"],
    "functionDoc": ["F1", "F1"],
    "gotoDefinition": ["F3", "F3"],
    "searchIncremental": ["Ctrl-F", "Command-F"],
    "searchReplace": ["Ctrl-Shift-F", "Command-Shift-F"],
    "findModule": ["F4", "F4"],
    "indentOrParam": ["Tab", "Tab"],
    "escape": ["Esc", "Esc"],
    "dbManager": ["Ctrl-Shift-M", "Command-Shift-M"],
    "toggleComment": ["Ctrl-Shift-C", "Command-Shift-C"],
    "synchronize": ["Alt-Shift-S", "Command-Option-S"],
    "preferences": ["Alt-Shift-P", "Ctrl-Command-P"],
    "openApp": ["Ctrl-Alt-R", "Command-Option-R"]
}
