name: Commit lint
run-name: Linting commit messages

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lint:
    name: Lint commit messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - run: npm ci --omit=optional
      - run: npx commitlint --from=${{ github.event.pull_request.base.sha }}
