name: Semantic Release

on:
  workflow_run:
    workflows: [test]
    branches: [main]
    types:
      - completed

permissions:
  contents: read

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - run: npm ci --omit=optional
      - run: npm run build
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
